### ISSUE TITLE
Can not uninstall.

### ISSUE THREAD

**Issue by tosintech-web** [humhub-contrib/fcm-push#12] opened 2022-05-29 15:20 UTC
If you try to uninstall, it's caused internal server error.
```
yii\base\UnknownMethodException: Calling unknown method: humhub\modules\fcmPush\Module::getPath() in /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Component.php:301
Stack trace:
#0 /var/www/localhost/htdocs/protected/humhub/modules/admin/controllers/ModuleController.php(192): yii\base\Component->__call()
#1 [internal function]: humhub\modules\admin\controllers\ModuleController->actionRemove()
#2 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#3 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#4 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction()
#5 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#6 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#7 /var/www/localhost/htdocs/index.php(25): yii\base\Application->run()
#8 {main}
```

It seems to not being "getPath()" method. What should we do?

**Comment by yurabakhtin** [comment] 2022-05-31 13:14
@luke- Fixed in core PR https://github.com/humhub/humhub/pull/5734, the bug was only for module with not writable folder.

@tosintech-web Thank you for the report!

**Comment by yurabakhtin** [comment] 2022-06-01 10:03
@luke- Yes probably it is not a bug, because the case when module folder is not writable is very rarely, but we should merge the PR in order to have clear error message.

**Comment by luke-** [comment] 2022-06-02 11:11
@yurabakhtin Thanks!

**Closed by luke-** 2022-06-02 11:11 UTC
